# Precompute expensive vignettes for CRAN.
#
# The heaviest vignettes refit `ackwards()` on the full bfi25 polychoric basis
# (and run parallel analysis, split-half comparability, and bootstrap edges) on
# every build. CRAN flagged the resulting re-build time (~317s) as too costly to
# check regularly. To fix this without dumbing down the examples, those vignettes
# are authored as `*.Rmd.orig` and knitted *here*, ahead of time, into plain
# `*.Rmd` with all results and figures baked in. R then builds those `*.Rmd`
# with pandoc only (near-zero cost) -- the R code never re-runs on CRAN.
#
# This is the rOpenSci precompute pattern:
#   https://ropensci.org/blog/2019/12/08/precompute-vignettes/
#
# Vignettes that stay live (built normally on CRAN) have no `.Rmd.orig`:
#   - ackwards-interpret.Rmd (bfi25 subset; needs IPIP labels; already ~2s)
#
# sim16 was considered for the live set but degrades the two candidates: the
# girard vignette's comparability lesson needs realistically messy data, and the
# visualization reference needs above-threshold negative edges to demo the
# sign-encoding aesthetics -- sim16's clean planted structure has neither.
#
# USAGE: run from the package root after editing any `*.Rmd.orig` AND before
# every release (the generated `*.Rmd` + `figure/` must be committed):
#
#   Rscript vignettes/precompute.R
#
# Requires the Suggests stack (lavaan, ggplot2, gt, EFAtools) so the ESEM,
# plotting, and CD chunks bake in real output.

stopifnot(file.exists("DESCRIPTION")) # must run from package root

devtools::load_all(".", quiet = TRUE)

old_wd <- setwd("vignettes")
on.exit(setwd(old_wd), add = TRUE)

orig_files <- list.files(pattern = "\\.Rmd\\.orig$")
if (length(orig_files) == 0L) {
  stop("No *.Rmd.orig files found in vignettes/.")
}

# Insert a freshness stamp just below the generated .Rmd's YAML header: an HTML
# comment (invisible to pandoc) carrying the source filename and the md5 of the
# .Rmd.orig it was knitted from. tools/check-vignette-freshness.R re-derives the
# md5 and fails if a .Rmd.orig was edited without re-running this script, turning
# a stale-output slip from a prose warning into a mechanical CI failure (M65).
stamp_rmd <- function(rmd, orig) {
  md5 <- unname(tools::md5sum(orig))
  lines <- readLines(rmd, warn = FALSE)
  # YAML header is the block between the first two `---` fence lines.
  fences <- which(lines == "---")
  if (length(fences) < 2L) {
    stop("No YAML header found in ", rmd, "; cannot insert freshness stamp.")
  }
  stamp <- c(
    "",
    "<!-- Generated by vignettes/precompute.R; DO NOT EDIT BY HAND.",
    sprintf("     Edit %s and re-run `Rscript vignettes/precompute.R`.", orig),
    "     Freshness is enforced by tools/check-vignette-freshness.R (M65). -->",
    sprintf("<!-- precompute-stamp: source=%s md5=%s -->", orig, md5)
  )
  writeLines(append(lines, stamp, after = fences[2L]), rmd)
}

for (f in orig_files) {
  base <- sub("\\.Rmd\\.orig$", "", f)
  rmd <- paste0(base, ".Rmd")
  message("Precomputing ", f, " -> ", rmd)
  # Unique figure prefix per vignette so the shared assets/ dir never collides
  # on common chunk labels (e.g. "setup"). The directory is deliberately NOT
  # named "figure"/"figures": R CMD check flags those as leftover knitr output.
  knitr::opts_chunk$set(fig.path = file.path("assets", paste0(base, "-")))
  knitr::knit(f, output = rmd, quiet = TRUE)
  stamp_rmd(rmd, f)
}

message("Done. Commit the generated *.Rmd and vignettes/assets/.")
